sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e3d8c81e8b71_key -iv $encrypted_e3d8c81e8b71_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker build -t ekevalo/coral-velocity-239303 -f Dockerfile.dev .
script:
- docker run -e CI=true ekevalo/coral-velocity-239303 npm run test -- --watchAll=false
deploy:
  provider: gae
  keyfile: client-secret.json.enc
  project: coral-velocity-239303
  on:
    branch: master
