sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fa4b663dc460_key -iv $encrypted_fa4b663dc460_iv
  -in coral-velocity-239303-3eaa829512de.json.enc -out coral-velocity-239303-3eaa829512de.json
  -d
- docker build -t ekevalo/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true ekevalo/docker-react npm run test -- --watchAll=false
deploy:
  provider: gae
  keyfile: coral-velocity-239303-3eaa829512de.json
  project: coral-velocity-239303
  on:
    branch: master
