sudo: required
services:
- docker
before_install:
- docker build -t ekevalo/coral-velocity-239303 -f Dockerfile.dev .
script:
- docker run -e CI=true ekevalo/coral-velocity-239303 npm run test -- --watchAll=false
deploy:
  provider: gae
  keyfile: client-secret.json
  project: docker-react
  on:
    branch: master
